# -*- coding: utf-8 -*
import wikipedia
text_file = open("Virginia_Clinton_Kelley.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Virginia_Clinton_Kelley").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Virginia_Clinton_Kelley").content)
text_file.close()
text_file = open("Lil_Stoner.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Lil_Stoner").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Lil_Stoner").content)
text_file.close()
text_file = open("Raymond_Brownell.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Raymond_Brownell").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Raymond_Brownell").content)
text_file.close()
text_file = open("John_McCauley.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("John_McCauley").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("John_McCauley").content)
text_file.close()
text_file = open("Winfield_Scott_Hancock.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Winfield_Scott_Hancock").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Winfield_Scott_Hancock").content)
text_file.close()
text_file = open("Lou_Spence.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Lou_Spence").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Lou_Spence").content)
text_file.close()
text_file = open("Knut_Steen.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Knut_Steen").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Knut_Steen").content)
text_file.close()
text_file = open("Dilma_Rousseff.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Dilma_Rousseff").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Dilma_Rousseff").content)
text_file.close()
text_file = open("Wilhelmina_of_the_Netherlands.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Wilhelmina_of_the_Netherlands").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Wilhelmina_of_the_Netherlands").content)
text_file.close()
text_file = open("Juliana_of_the_Netherlands.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Juliana_of_the_Netherlands").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Juliana_of_the_Netherlands").content)
text_file.close()
text_file = open("Buster_Keaton.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Buster_Keaton").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Buster_Keaton").content)
text_file.close()
text_file = open("Louis_Pasteur.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Louis_Pasteur").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Louis_Pasteur").content)
text_file.close()
text_file = open("Theodore_Roosevelt.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Theodore_Roosevelt").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Theodore_Roosevelt").content)
text_file.close()
text_file = open("John_Muir.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("John_Muir").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("John_Muir").content)
text_file.close()
text_file = open("Vincent_van_Gogh_(Russell_painting).txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Vincent_van_Gogh_(Russell_painting)").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Vincent_van_Gogh_(Russell_painting)").content)
text_file.close()
text_file = open("Beppe_Grillo.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Beppe_Grillo").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Beppe_Grillo").content)
text_file.close()
text_file = open("Edward_VI_of_England.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Edward_VI_of_England").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Edward_VI_of_England").content)
text_file.close()
text_file = open("Frances_Densmore.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Frances_Densmore").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Frances_Densmore").content)
text_file.close()
text_file = open("Eric_A._Havelock.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Eric_A._Havelock").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Eric_A._Havelock").content)
text_file.close()
text_file = open("Prince_Henry_the_Navigator.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Prince_Henry_the_Navigator").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Prince_Henry_the_Navigator").content)
text_file.close()
text_file = open("Antonio_Vivaldi.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Antonio_Vivaldi").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Antonio_Vivaldi").content)
text_file.close()
text_file = open("Knute_Rockne.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Knute_Rockne").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Knute_Rockne").content)
text_file.close()
text_file = open("Nikolai_Gogol.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Nikolai_Gogol").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Nikolai_Gogol").content)
text_file.close()
text_file = open("Jesse_Chisholm.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Jesse_Chisholm").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Jesse_Chisholm").content)
text_file.close()
text_file = open("Joseph_Henry_Shorthouse.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Joseph_Henry_Shorthouse").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Joseph_Henry_Shorthouse").content)
text_file.close()
text_file = open("Henry_VI_of_England.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Henry_VI_of_England").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Henry_VI_of_England").content)
text_file.close()
text_file = open("Frédéric_Chopin.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Frédéric_Chopin").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Frédéric_Chopin").content)
text_file.close()
text_file = open("Allan_Pinkerton.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Allan_Pinkerton").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Allan_Pinkerton").content)
text_file.close()
text_file = open("John_Alexander_McClernand.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("John_Alexander_McClernand").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("John_Alexander_McClernand").content)
text_file.close()
text_file = open("Edgar Allan Poe.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Edgar Allan Poe").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Edgar Allan Poe").content)
text_file.close()
text_file = open("Antanas Smetona.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Antanas Smetona").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Antanas Smetona").content)
text_file.close()
text_file = open("Golda Meir.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Golda Meir").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Golda Meir").content)
text_file.close()
text_file = open("Buffalo Bill.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Buffalo Bill").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Buffalo Bill").content)
text_file.close()
text_file = open("Sitting Bull.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Sitting Bull").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Sitting Bull").content)
text_file.close()
text_file = open("Tōyō Miyatake.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Tōyō Miyatake").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Tōyō Miyatake").content)
text_file.close()
text_file = open("Zishe Breitbart.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Zishe Breitbart").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Zishe Breitbart").content)
text_file.close()
text_file = open("Robert William Thomson.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Robert William Thomson").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Robert William Thomson").content)
text_file.close()
text_file = open("Frederick III, German Emperor.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Frederick III, German Emperor").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Frederick III, German Emperor").content)
text_file.close()
text_file = open("Elizabeth II of the United Kingdom.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Elizabeth II of the United Kingdom").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Elizabeth II of the United Kingdom").content)
text_file.close()
text_file = open("Javier Solana.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Javier Solana").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Javier Solana").content)
text_file.close()
text_file = open("Lillian Gish.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Lillian Gish").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Lillian Gish").content)
text_file.close()
text_file = open("Enrico Caruso.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Enrico Caruso").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Enrico Caruso").content)
text_file.close()
text_file = open("Marguerite de Navarre.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Marguerite de Navarre").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Marguerite de Navarre").content)
text_file.close()
text_file = open("T206 Honus Wagner.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("T206 Honus Wagner").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("T206 Honus Wagner").content)
text_file.close()
text_file = open("Jean-Baptiste Carpeaux.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Jean-Baptiste Carpeaux").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Jean-Baptiste Carpeaux").content)
text_file.close()
text_file = open("Fridtjof Nansen.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Fridtjof Nansen").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Fridtjof Nansen").content)
text_file.close()
text_file = open("Wayne Gretzky.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Wayne Gretzky").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Wayne Gretzky").content)
text_file.close()
text_file = open("Chandos portrait.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Chandos portrait").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Chandos portrait").content)
text_file.close()
text_file = open("Alice Manfield.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Alice Manfield").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Alice Manfield").content)
text_file.close()
text_file = open("Maxim Gorky.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Maxim Gorky").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Maxim Gorky").content)
text_file.close()
text_file = open("Francisco Goya.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Francisco Goya").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Francisco Goya").content)
text_file.close()
text_file = open("Frank_Sinatra.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Frank_Sinatra").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Frank_Sinatra").content)
text_file.close()
text_file = open("John Henry Newman.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("John Henry Newman").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("John Henry Newman").content)
text_file.close()
text_file = open("Billy Strayhorn.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Billy Strayhorn").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Billy Strayhorn").content)
text_file.close()
text_file = open("Walt Whitman.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Walt Whitman").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Walt Whitman").content)
text_file.close()
text_file = open("Alice Paul.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Alice Paul").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Alice Paul").content)
text_file.close()
text_file = open("Rory Kennedy.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Rory Kennedy").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Rory Kennedy").content)
text_file.close()
text_file = open("Aminah Cendrakasih.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Aminah Cendrakasih").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Aminah Cendrakasih").content)
text_file.close()
text_file = open("Keith_Miller.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Keith_Miller").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Keith_Miller").content)
text_file.close()
text_file = open("Margaret_Murray.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Margaret_Murray").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Margaret_Murray").content)
text_file.close()
text_file = open("Jocelin_of_Glasgow.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Jocelin_of_Glasgow").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Jocelin_of_Glasgow").content)
text_file.close()
text_file = open("Donald_Forrester_Brown.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Donald_Forrester_Brown").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Donald_Forrester_Brown").content)
text_file.close()
text_file = open("Robert_Peake_the_Elder.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Robert_Peake_the_Elder").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Robert_Peake_the_Elder").content)
text_file.close()
text_file = open("Edgar_Towner.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Edgar_Towner").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Edgar_Towner").content)
text_file.close()
text_file = open("August_Meyszner.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("August_Meyszner").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("August_Meyszner").content)
text_file.close()
text_file = open("Edward_VIII.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Edward_VIII").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Edward_VIII").content)
text_file.close()
text_file = open("William_Hanna.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("William_Hanna").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("William_Hanna").content)
text_file.close()
text_file = open("Charles_II_of_England.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Charles_II_of_England").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Charles_II_of_England").content)
text_file.close()
text_file = open("William_Sterling_Parsons.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("William_Sterling_Parsons").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("William_Sterling_Parsons").content)
text_file.close()
text_file = open("Galen.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Galen").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Galen").content)
text_file.close()
text_file = open("Buffalo_Bill.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Buffalo_Bill").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Buffalo_Bill").content)
text_file.close()
text_file = open("Antanas_Smetona.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Antanas_Smetona").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Antanas_Smetona").content)
text_file.close()
text_file = open("Leonhard_Euler.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Leonhard_Euler").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Leonhard_Euler").content)
text_file.close()
text_file = open("Emil_von_Behring.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Emil_von_Behring").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Emil_von_Behring").content)
text_file.close()
text_file = open("Santiago_Ramón_y_Cajal.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Santiago_Ramón_y_Cajal").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Santiago_Ramón_y_Cajal").content)
text_file.close()
text_file = open("Maria_Mitchell.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Maria_Mitchell").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Maria_Mitchell").content)
text_file.close()
text_file = open("Calvin_Coolidge.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Calvin_Coolidge").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Calvin_Coolidge").content)
text_file.close()
text_file = open("Michio_Kaku.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Michio_Kaku").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Michio_Kaku").content)
text_file.close()
text_file = open("Isaac_Newton.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Isaac_Newton").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Isaac_Newton").content)
text_file.close()
text_file = open("Richard_Feynman.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Richard_Feynman").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Richard_Feynman").content)
text_file.close()
text_file = open("Macfarlane_Burnet.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Macfarlane_Burnet").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Macfarlane_Burnet").content)
text_file.close()
text_file = open("Rosalind_Franklin.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Rosalind_Franklin").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Rosalind_Franklin").content)
text_file.close()
text_file = open("Georg_Forster.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Georg_Forster").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Georg_Forster").content)
text_file.close()
text_file = open("Barbara_McClintock.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Barbara_McClintock").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Barbara_McClintock").content)
text_file.close()
text_file = open("Carl_Friedrich_Gauss.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Carl_Friedrich_Gauss").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Carl_Friedrich_Gauss").content)
text_file.close()
text_file = open("Nguyễn_Ngọc_Thơ.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Nguyễn_Ngọc_Thơ").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Nguyễn_Ngọc_Thơ").content)
text_file.close()
text_file = open("Albert_Einstein.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Albert_Einstein").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Albert_Einstein").content)
text_file.close()
text_file = open("Leonardo_da_Vinci.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Leonardo_da_Vinci").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Leonardo_da_Vinci").content)
text_file.close()
text_file = open("Werner_Heisenberg.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Werner_Heisenberg").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Werner_Heisenberg").content)
text_file.close()
text_file = open("Cosmo_Gordon_Lang.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Cosmo_Gordon_Lang").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Cosmo_Gordon_Lang").content)
text_file.close()
text_file = open("Vesna_Vulović.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Vesna_Vulović").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Vesna_Vulović").content)
text_file.close()
text_file = open("Ed_Stelmach.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Ed_Stelmach").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Ed_Stelmach").content)
text_file.close()
text_file = open("Elizabeth_Willing_Powel.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Elizabeth_Willing_Powel").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Elizabeth_Willing_Powel").content)
text_file.close()
text_file = open("Hilda_Annetta_Walker.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Hilda_Annetta_Walker").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Hilda_Annetta_Walker").content)
text_file.close()
text_file = open("David_Cameron.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("David_Cameron").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("David_Cameron").content)
text_file.close()
text_file = open("Grover_Cleveland.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Grover_Cleveland").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Grover_Cleveland").content)
text_file.close()
text_file = open("Zhou_Enlai.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Zhou_Enlai").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Zhou_Enlai").content)
text_file.close()
text_file = open("Józef_Piłsudski.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Józef_Piłsudski").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Józef_Piłsudski").content)
text_file.close()
text_file = open("Nikita_Khrushchev.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Nikita_Khrushchev").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Nikita_Khrushchev").content)
text_file.close()
text_file = open("Winston_Churchill.txt", "w", encoding='utf-8')
text_file.write(wikipedia.page("Winston_Churchill").title)
text_file.write("\n")
text_file.write("\n")
text_file.write(wikipedia.page("Winston_Churchill").content)
text_file.close()

